Feat: 모바일 UI bottomSheet,메인화면 리스트 무한스크롤
2024TeamUnity/Goods_FE pull request #85
Opened 2024-06-09 04:44 UTC by DxxxHxx

### 의존성 추가
```
npm i framer-motion
```
### ⭐ PR 유형

어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 문서 추가
- [ ] 테스트 추가, 테스트 리팩토링
- [x] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 📌 관련 이슈

### ✨ 변경 사항

- 모바일 화면 UI개선을 위해 메인화면 리스트를 bottom sheet로 변경 했습니다.
- 메인화면 리스트에 무한 스크롤을 추가 했습니다.
- 마커도 페이지 별로 뜨고 있는데, 백엔드에서 전체를 받아오는 api가 추가 되면 수정 할 예정입니다.
- 현재 마커를 클릭하거나 검색 결과를 볼 때 리스트에 해당 상품만 뜨도록 돼 있는데, 이전의 요청으로 받은 데이터 중 위치 값이 일치하는 정보들만 프론트에서 필터링 해 띄우는 방식으로 구현 되어 있었습니다. 
 그러다 보니 페이지 형식이 아니게 되어서 마커를 클릭했을 때, 검색 결과를 볼 때는 무한 스크롤이 불가능 한 상황입니다. 
 그래서 마커를 클릭 할 때마다 서버에 요청을 보내서 페이지 형식으로 받아야 하나 생각을 해봤는데, 이에 대해서 어떻게 해결해야 할지 상의 해봐야 할 것 같습니다. 

### 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

2024-06-09 07:28 UTC, jhLeedev requested changes

2024-06-09 07:28 UTC, jhLeedev commented on src/util/useBottomSheet.ts
> +    const shouldClose = info?.y > 20 || (info?.y >= 0 && info.y > 45);
- y > 45 가 참이면 y > 20 랑 y >= 0 은 항상 참이지 않나요? 정확히 어떤 기준으로 나누신 것인지는 모르지만 다시 검토해주시면 감사하겠습니다!

- > 현재 마커를 클릭하거나 검색 결과를 볼 때 리스트에 해당 상품만 뜨도록 돼 있는데, 이전의 요청으로 받은 데이터 중 위치 값이 일치하는 정보들만 프론트에서 필터링 해 띄우는 방식으로 구현 되어 있었습니다.
그러다 보니 페이지 형식이 아니게 되어서 마커를 클릭했을 때, 검색 결과를 볼 때는 무한 스크롤이 불가능 한 상황입니다.
그래서 마커를 클릭 할 때마다 서버에 요청을 보내서 페이지 형식으로 받아야 하나 생각을 해봤는데, 이에 대해서 어떻게 해결해야 할지 상의 해봐야 할 것 같습니다.
  - 이미 페이지 형식으로 받아오는 것을 기준으로 리스트를 구현해놓았기 때문에 마커도 클릭할 때마다 서버에서 페이지 형식을 받아오는 게 제일 좋을 것 같긴 합니다. 백엔드 분들께 새 api를 추가해달라고 부탁드려야 할까요?

2024-06-10 03:29 UTC, DxxxHxx commented on src/util/useBottomSheet.ts
> +    const shouldClose = info?.y > 20 || (info?.y >= 0 && info.y > 45);
- 수정하려고 했는데 어제부터 서버 통신이 안돼서 수정이 안되고 있습니다, 혹시 저만 그런가요 ? ㅠㅠ
- 다른 더 좋은 방법이 없다면 그렇게 해야 할 것 같아요. 오늘 스프린트 때 얘기 해보면 좋을 것 같습니다.

2024-06-12 08:30 UTC, jhLeedev approved these changes

2024-06-12 08:30 UTC, merged